--
- name: Shibboleth-Proxy | Disco | Download | Plugin v{{ shibbolethproxy_discoplugin_version }}
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ shibbolethproxy_discoplugin_location }}/releases/download/{{ shibbolethproxy_discoplugin_version }}/shibboleth-idp-authn-discovery-{{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9.]', '') }}.tar.gz"
    remote_src: yes
    dest: "{{ shibbolethidp_idp_home }}"
  notify: rebuild shibboleth-idp

# - name: Shibboleth-Proxy Disco
# ===========================================

- name: Disco | Configure | AuthenticationFlow | authn/general-authn.xml
  blockinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    marker: "      <!-- {mark} ansible managed - Disco authentication flow ! KEEP ON TOP ! -->"
    insertafter: "shibboleth.AvailableAuthenticationFlows"
    block: |2
              <bean id="authn/Disco" parent="shibboleth.AuthenticationFlow"
                    p:nonBrowserSupported="false" p:forcedAuthenticationSupported="true"/>
  notify:
   - restart shibboleth-idp

- name: Disco | Configure | Flow | idp.properties
  lineinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/idp.properties"
    regexp: ^(?!.*Disco)(idp.authn.flows=.*)$
    line: \1|Disco
    backrefs: yes
