- name: Disco | Download | Plugin v{{ shibbolethproxy_discoplugin_version }}
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ shibbolethproxy_discoplugin_location }}/releases/download/{{ shibbolethproxy_discoplugin_version }}/shibboleth-idp-authn-discovery-{{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9.]', '') }}.tar.gz"
    remote_src: yes
    dest: "{{ shibbolethidp_idp_home }}"
    creates: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/idp-authn-api-discovery-{{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9.]', '') }}.jar"
    group: jetty
    owner: root
    mode: 0640
  notify: rebuild shibboleth-idp

- name: Disco | Detect | Duplicate | Plugins
  find:
    paths: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib"
    patterns: "^(?!.*({{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9.]', '') }})).*discovery"
    use_regex: true
  register: files_to_delete

- name: Disco | Delete | Older | Plugins
  file:
    path: "{{ shibbolethproxy_item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  loop_control:
    loop_var: shibbolethproxy_item

# - name: Shibboleth-Proxy Disco
# ===========================================

- name: Disco | Configure | AuthenticationFlow | authn/general-authn.xml
  blockinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    marker: "      <!-- {mark} ansible managed - Disco authentication flow ! KEEP ON TOP ! -->"
    insertafter: "shibboleth.AvailableAuthenticationFlows"
    block: |2
              <bean id="authn/Disco" parent="shibboleth.AuthenticationFlow"
                    p:nonBrowserSupported="false" p:forcedAuthenticationSupported="true"/>
  notify:
   - restart shibboleth-idp

- name: Disco | Configure | Flow | idp.properties
  lineinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/idp.properties"
    regexp: ^(?!.*Disco)(idp.authn.flows=.*)$
    line: \1|Disco
    backrefs: yes

- name: Disco | Configure | AuthenticationMethods | relying-party.xml
  blockinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/relying-party.xml"
    marker: "      <!-- {mark} ansible managed - Disco authenticationMethods {{ shibbolethproxy_item.ids }} -->"
    insertafter: "shibboleth.RelyingPartyOverrides"
    block: |2
          <bean parent="{{ shibbolethproxy_item.parent }}" p:responderIdLookupStrategy-ref="profileResponderIdLookupFunction" c:relyingPartyIds="{{ shibbolethproxy_item.ids }}">
            <property name="profileConfigurations">
              <list>
                <bean parent="SAML2.SSO" p:authenticationFlows="{{ shibbolethproxy_item.flows }}" />   
                <bean parent="OIDC.SSO" p:authenticationFlows="{{ shibbolethproxy_item.flows }}" />
              </list>
            </property>
          </bean>
  with_items: "{{ shibbolethproxy_authmethods }}"
  loop_control:
    loop_var: shibbolethproxy_item

