- name: MPASSid | authnid | Download | Plugin v{{ shibbolethproxy_authnid_version }}
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ shibbolethproxy_authnid_location }}/releases/download/{{ shibbolethproxy_authnid_version }}/shibboleth-idp-attribute-authnid-{{ shibbolethproxy_authnid_version | regex_replace('[^0-9.]', '') }}.tar.gz"
    remote_src: yes
    dest: "{{ shibbolethidp_idp_home }}"
    creates: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/idp-attribute-impl-authnid-{{ shibbolethproxy_authnid_version | regex_replace('[^0-9.]', '') }}.jar"
    group: jetty
    owner: root
    mode: 0640
  notify: rebuild shibboleth-idp

- name: MPASSid | authnid | Detect | Duplicate | Plugins
  find:
    paths: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib"
    patterns: "^(?!.*({{ shibbolethproxy_authnid_version | regex_replace('[^0-9.]', '') }})).*authnid"
    use_regex: true
  register: files_to_delete

- name: MPASSid | authnid | Delete | Older | Plugins
  file:
    path: "{{ shibbolethproxy_item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  loop_control:
    loop_var: shibbolethproxy_item
