- name: Disco | Download | Plugin v{{ shibbolethproxy_discoplugin_version }}
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ shibbolethproxy_discoplugin_location }}/releases/download/{{ shibbolethproxy_discoplugin_version }}/shibboleth-idp-authn-discovery-{{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9rc.-]', '') }}.tar.gz"
    remote_src: yes
    dest: "{{ shibbolethidp_idp_home }}"
    creates: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/idp-authn-api-discovery-{{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9rc.-]', '') }}.jar"
    group: jetty
    owner: root
    mode: 0640
  notify: rebuild shibboleth-idp

- name: Disco | Detect | Duplicate | Plugins
  find:
    paths: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib"
    patterns: "^(?!.*({{ shibbolethproxy_discoplugin_version | regex_replace('[^0-9rc.-]', '') }})).*discovery"
    use_regex: true
  register: files_to_delete

- name: Disco | Delete | Older | Plugins
  file:
    path: "{{ shibbolethproxy_item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  loop_control:
    loop_var: shibbolethproxy_item

# - name: Shibboleth-Proxy Disco
# ===========================================

#- name: Disco | Configure | AuthenticationFlow | authn/general-authn.xml
#  blockinfile:
#    dest: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
#    marker: "      <!-- {mark} ansible managed - Disco authentication flow ! KEEP ON TOP ! -->"
#    insertafter: "shibboleth.AvailableAuthenticationFlows"
#    block: |2
#              <bean id="authn/Disco" parent="shibboleth.AuthenticationFlow"
#                    p:nonBrowserSupported="false" p:forcedAuthenticationSupported="true"/>
#  notify:
#   - restart shibboleth-idp

- name: Configure | Proxy | Del | AuthenticationFlows < authn/general-authn.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    xpath: /x:beans/x:bean[@id='authn/Disco']
    namespaces:
      x: "http://www.springframework.org/schema/beans"
    state: absent

- name: Disco | Configure | AuthenticationFlow | authn/general-authn.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    xpath: /x:beans/x:bean[@id='authn/SAML']
    pretty_print: yes
    insertbefore: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      p: "http://www.springframework.org/schema/p"
      c: "http://www.springframework.org/schema/c"
    add_children:
      - bean:
          id: "authn/Disco"
          parent: "shibboleth.AuthenticationFlow"
          "{http://www.springframework.org/schema/p}nonBrowserSupported": "false"
          "{http://www.springframework.org/schema/p}forcedAuthenticationSupported": "true"
          _:
            - property: 
                name: supportedPrincipals
                _:
                  - list:
                      _:
                         - bean:
                             parent: shibboleth.SAML2AuthnContextClassRef
                             "{http://www.springframework.org/schema/c}classRef": https://refeds.org/profile/sfa
                         - bean:
                             parent: shibboleth.OIDCAuthnContextClassReference
                             "{http://www.springframework.org/schema/c}classRef": https://refeds.org/profile/sfa
                         - bean:
                             parent: shibboleth.SAML2AuthnContextClassRef
                             "{http://www.springframework.org/schema/c}classRef": https://refeds.org/profile/mfa
                         - bean:
                             parent: shibboleth.OIDCAuthnContextClassReference
                             "{http://www.springframework.org/schema/c}classRef": https://refeds.org/profile/mfa

- name: Disco | Configure | Flow | idp.properties
  lineinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/idp.properties"
    regexp: ^(?!.*Disco)(idp.authn.flows=.*)$
    line: \1|Disco
    backrefs: yes

- name: Configure | Proxy | Del | AuthenticationMethods < conf/relying-party.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/relying-party.xml"
    xpath: //x:bean[@c:relyingPartyIds="{{ shibbolethproxy_item.ids }}"]
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      c: "http://www.springframework.org/schema/c"
    state: absent
  loop_control:
    loop_var: shibbolethproxy_item
  with_items: "{{ shibbolethproxy_authmethods }}"

- name: Configure | Proxy | Add | AuthenticationMethods > conf/relying-party.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/relying-party.xml"
    xpath: //util:list[@id='shibboleth.RelyingPartyOverrides']
    pretty_print: yes
    #    insertbefore: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      p: "http://www.springframework.org/schema/p"
      c: "http://www.springframework.org/schema/c"
      util: "http://www.springframework.org/schema/util" 
    add_children:
      - bean:
          parent: "{{ shibbolethproxy_item.parent }}"
          #"{http://www.springframework.org/schema/p}responderIdLookupStrategy-ref": "profileResponderIdLookupFunction"
          "{http://www.springframework.org/schema/c}relyingPartyIds": "{{ shibbolethproxy_item.ids }}"
          _:
            - property:
                name: profileConfigurations
                _:
                   - list:
                       _:
                          - bean:
                              parent: "SAML2.SSO"
                              "{http://www.springframework.org/schema/p}authenticationFlows": "{{ shibbolethproxy_item.flows }}"
                          - bean:
                              parent: "OIDC.SSO"
                              "{http://www.springframework.org/schema/p}acrRequestAlwaysEssential": "true"
                              "{http://www.springframework.org/schema/p}authenticationFlows": "{{ shibbolethproxy_item.flows }}"
                          - bean:
                              parent: "OIDC.UserInfo"
  loop_control:
    loop_var: shibbolethproxy_item
  with_items: "{{ shibbolethproxy_authmethods }}"

